### ISSUE TITLE
Change font size in mglearn.tools.visualize_coefficients

### ISSUE THREAD

**Issue by newframer** [amueller/introduction_to_ml_with_python#52] opened 2017-10-11 18:53 UTC
Hi Andreas, 

I really like the book and use it for my own project. Now, one quick question is about how to change the font size in this code 
`mglearn.tools.visualize_coefficients(coef, feature_names, n_top_features=10)`

The picture is beautiful, but the font size is often too small for a presentation slide. 

Thanks.

**Comment by amueller** [comment] 2017-10-17 15:42
Usually I find it easier to increase the DPI of the figure instead of increasing the font size. You can do that with
``plt.figure(dpi=300)`` before building the plot.

**Comment by amueller** [comment] 2017-10-17 15:43
The "preamble.py" of the notebooks actually changes this setting for all plots.

**Comment by wendlingd** [comment] 2018-05-20 17:45
I'm making a lot of progress with your book, many thanks. I am working with the below from chap 7 p 355, in the spyder editor. Changing the dpi in preamble.py gives me SOME control of the plot WHEN I display in the Console; however, the text still overwrites the bars. The text is huge in all the plots I have tried, when spyder opens it in a separate window. Where in your files might I add a way to control the font size more directly? I have tried some matplotlib doc examples, trying to put something like labelsize=11 into various places; has not worked.

`
fig, ax = plt.subplots(1, 2, figsize=(10, 10))
topic_names = ["{:>2} ".format(i) + " ".join(words)
               for i, words in enumerate(feature_names[sorting[:, :2]])]
# two column bar chart:
for col in [0, 1]:
    start = col * 50
    end = (col + 1) * 50
    ax[col].barh(np.arange(50), np.sum(document_topics100, axis=0)[start:end])
    ax[col].set_yticks(np.arange(50))
    ax[col].set_yticklabels(topic_names[start:end], ha="left", va="top")
    ax[col].invert_yaxis()
    ax[col].set_xlim(0, 2000)
    yax = ax[col].get_yaxis()
    yax.set_tick_params(pad=130)
plt.tight_layout()
`
![fontsize](https://user-images.githubusercontent.com/10210191/40281776-704b56a6-5c33-11e8-8869-8c09b9503eca.png)

**Comment by amueller** [comment] 2018-05-20 17:52
you can change the figure size. If you make it bigger, the font will get smaller (in relation to the plot).

**Comment by amueller** [comment] 2018-10-09 03:46
Closing this as I feel the issue is resolved. Feel free to reopen.

**Closed by amueller** 2018-10-09 03:46 UTC
